## YAML Template.
language: java
before_install:
    - cd ..
    - git clone --branch=$TRAVIS_BRANCH git://github.com/CharltonIT/openvpms.git openvpms
    - git clone --branch=$TRAVIS_BRANCH git://github.com/CharltonIT/maven-plugins.git maven-plugins
    - git clone --branch=$TRAVIS_BRANCH git://github.com/CharltonIT/Openvpms-esci-adapter.git openvpms-esci-adapter
    - git clone --branch=$TRAVIS_BRANCH git://github.com/CharltonIT/Openvpms-etl.git openvpms-etl
    - git clone --branch=$TRAVIS_BRANCH git://github.com/CharltonIT/Openvpms-framework.git openvpms-framework
    - git clone --branch=$TRAVIS_BRANCH git://github.com/CharltonIT/Openvpms-reports.git openvpms-reports
    - git clone --branch=$TRAVIS_BRANCH git://github.com/CharltonIT/openvpms-web.git openvpms-web
    - git clone --branch=$TRAVIS_BRANCH git://github.com/CharltonIT/openvpms-sms.git openvpms-sms
    - git clone --branch=$TRAVIS_BRANCH git://github.com/CharltonIT/openvpms-release.git openvpms-release
    - cd openvpms
    - mvn install -DskipTests=true 
    - cd openvpms-framework
    - mysql -u root < openvpms/src/test/resources/createdb.sql
    - cd $TRAVIS_BUILD_DIR
